import { resolveSpeciesMeta } from './speciesCatalog.js';

const PIPELINE = [
  'FAO',
  'ICRAF',
  'USDA',
  'GBIF',
  'India Biodiversity Portal',
  'Forest Survey of India',
];

function S(title, icon, short, sci, importance, example, fact, conserve) {
  return {
    title,
    icon,
    short_description: short,
    scientific_explanation: sci,
    importance,
    real_world_example: example,
    interesting_fact: fact,
    conservation_message: conserve,
    confidence: 'High (local species pack)',
  };
}

function pack(common, scientific, family, parts) {
  return {
    meta: { common, scientific, family },
    climate: (age, biomass, carbon, co2) => ({
      identification: S(
        'Tree Identification',
        'Trees',
        parts.idShort,
        parts.idSci,
        parts.idImp,
        parts.idEx,
        parts.idFact,
        parts.idCons
      ),
      taxonomy: S(
        'Taxonomy',
        'Compass',
        `Classification of ${common}`,
        `Scientific name: ${scientific}. Family: ${family}. Common name: ${common}.`,
        `Keeping taxonomy fixed to ${scientific} ensures every climatic claim stays species-true.`,
        parts.taxEx,
        parts.taxFact,
        `Protect named ${common} plantings so botanical identity is not lost in mixed street inventories.`
      ),
      description: S(
        'Botanical Description',
        'BookOpen',
        parts.descShort,
        parts.descSci,
        parts.descImp,
        parts.descEx,
        parts.descFact,
        parts.descCons
      ),
      habitat: S(
        'Habitat',
        'Compass',
        parts.habShort,
        parts.habSci,
        parts.habImp,
        parts.habEx,
        parts.habFact,
        parts.habCons
      ),
      distribution: S(
        'Geographic Distribution',
        'Globe',
        parts.distShort,
        parts.distSci,
        parts.distImp,
        parts.distEx,
        parts.distFact,
        parts.distCons
      ),
      climate_preference: S(
        'Climate Preference',
        'Thermometer',
        parts.climShort,
        parts.climSci,
        parts.climImp,
        parts.climEx,
        parts.climFact,
        parts.climCons
      ),
      soil: S(
        'Soil Requirements',
        'Leaf',
        parts.soilShort,
        parts.soilSci,
        parts.soilImp,
        parts.soilEx,
        parts.soilFact,
        parts.soilCons
      ),
      ecological_importance: S(
        'Ecological Importance',
        'Activity',
        parts.ecoShort,
        parts.ecoSci,
        parts.ecoImp,
        parts.ecoEx,
        parts.ecoFact,
        parts.ecoCons
      ),
      biodiversity_associations: S(
        'Biodiversity Associations',
        'Bird',
        parts.bioShort,
        parts.bioSci,
        parts.bioImp,
        parts.bioEx,
        parts.bioFact,
        parts.bioCons
      ),
      pollinators: S(
        'Pollinators',
        'Bug',
        parts.pollShort,
        parts.pollSci,
        parts.pollImp,
        parts.pollEx,
        parts.pollFact,
        parts.pollCons
      ),
      carbon_sequestration: S(
        'Carbon Sequestration',
        'Leaf',
        `Carbon stored by this ${common}`,
        `For this measured ${common} (${scientific}): age ${Number(age).toFixed(1)} years, aboveground biomass ${Number(biomass).toFixed(2)} kg, carbon ${Number(carbon).toFixed(2)} kg, CO₂ equivalent ${Number(co2).toFixed(2)} kg. ${parts.carbonSciExtra}`,
        `These values are calculated for this ${common} tree only — not a generic tropical average.`,
        parts.carbonEx,
        `Lifetime CO₂ captured by this ${common}: ~${Number(co2).toFixed(1)} kg.`,
        `Felling this ${common} risks releasing stored carbon and ending further sequestration.`
      ),
      climate_impact: S(
        'Climate Impact & Shading',
        'Zap',
        parts.shadeShort,
        `${parts.shadeSci} At ${Number(age).toFixed(1)} years this ${common} already holds ~${Number(biomass).toFixed(1)} kg biomass.`,
        parts.shadeImp,
        parts.shadeEx,
        parts.shadeFact,
        parts.shadeCons
      ),
      medicinal_uses: S(
        'Medicinal Uses',
        'Syringe',
        parts.medShort,
        parts.medSci,
        parts.medImp,
        parts.medEx,
        parts.medFact,
        parts.medCons
      ),
      cultural_spirituality: S(
        'Cultural & Spiritual Significance',
        'Heart',
        parts.culShort,
        parts.culSci,
        parts.culImp,
        parts.culEx,
        parts.culFact,
        parts.culCons
      ),
      diseases_pests: S(
        'Diseases & Pests',
        'ShieldAlert',
        parts.pestShort,
        parts.pestSci,
        parts.pestImp,
        parts.pestEx,
        parts.pestFact,
        parts.pestCons
      ),
      conservation_status: S(
        'Conservation Status',
        'ShieldCheck',
        parts.consShort,
        parts.consSci,
        parts.consImp,
        parts.consEx,
        parts.consFact,
        parts.consCons
      ),
      interesting_facts: S(
        'Interesting Facts',
        'Sparkles',
        parts.factShort,
        parts.factSci,
        parts.factImp,
        parts.factEx,
        parts.factFact,
        parts.factCons
      ),
      references: S(
        'References and Sources Used',
        'Info',
        `Research pipeline: ${PIPELINE.join(' → ')} → Local species pack`,
        `Local offline pack for ${common} (${scientific}) curated from FAO, ICRAF, USDA, GBIF, India Biodiversity Portal, and Forest Survey of India framing.`,
        `Offline packs keep the Climatic Impact page demo-ready without live Gemini quota.`,
        `Re-run Calculate on any dropdown species to load that species’ local pack.`,
        `Pipeline sources: ${PIPELINE.join(', ')}.`,
        `Retain source-backed stewardship notes with ${common} inventory records.`
      ),
      research_pipeline: PIPELINE,
    }),
    medicinal: parts.medicinalJson,
    habitat: parts.habitatJson,
  };
}

const PACKS = {
  Mango: pack('Mango', 'Mangifera indica', 'Anacardiaceae', {
    idShort: 'How to recognize Mango',
    idSci: 'Mangifera indica is an evergreen to semi-evergreen fruit tree with a dense rounded crown, simple alternate leaves, panicle flowers, and fleshy drupe fruits.',
    idImp: 'Correct mango ID keeps fruit, medicinal, and carbon claims tied to Mangifera indica only.',
    idEx: 'Orchard and avenue surveys list mango under Mangifera indica for cultivar tracking.',
    idFact: 'Local name Aam is widely used across India for mango.',
    idCons: 'Replacing mature mango with unrelated ornamentals erases a verified fruit-tree carbon asset.',
    taxEx: 'GBIF and USDA-style checklists accept Mangifera indica in Anacardiaceae.',
    taxFact: 'Genus Mangifera includes several species; cultivated mango is primarily M. indica.',
    descShort: 'Physical form of Mango',
    descSci: 'Medium–large canopy tree (often 10–30 m), dense shade crown, leathery leaves, and seasonally heavy flowering/fruiting.',
    descImp: 'Crown form controls shade cooling and where birds/frugivores forage on mango.',
    descEx: 'Field teams confirm mango by leaf and fruit traits during GBH surveys.',
    descFact: 'Mango wood density and canopy make it a strong urban shade species.',
    descCons: 'Cutting a mature mango removes decades of canopy architecture.',
    habShort: 'Where Mango grows best',
    habSci: 'Tropical to subtropical orchards, farm boundaries, and homestead gardens; prefers deep, well-drained loams; sensitive to frost and waterlogging.',
    habImp: 'Right site matching raises mango survival and long-term biomass gain.',
    habEx: 'ICRAF-style agroforestry places mango on farm boundaries for fruit + shade.',
    habFact: 'Frost damages young mango flush more than mature wood.',
    habCons: 'Planting mango in waterlogged pits causes root failure.',
    distShort: 'Where Mango is recorded',
    distSci: 'Native/long-cultivated across South Asia with extensive cultivated occurrences worldwide (GBIF-dense in India).',
    distImp: 'Knowing mango’s cultivated range guides orchard vs wild conservation priorities.',
    distEx: 'India Biodiversity Portal records cluster around villages, orchards, and towns.',
    distFact: 'India holds exceptional cultivar diversity for mango.',
    distCons: 'Local landraces are more resilient than random nursery stock.',
    climShort: 'Climate niche of Mango',
    climSci: 'Warm tropical/subtropical climates with a dry spell that helps flowering; prolonged cold is limiting.',
    climImp: 'Climate fit decides whether mango keeps fruiting and sequestering carbon.',
    climEx: 'FAO horticulture notes use climate envelopes for mango suitability.',
    climFact: 'Distinct dry/wet seasons often improve flowering regularity.',
    climCons: 'Heat + drought without irrigation can drop fruit set and growth.',
    soilShort: 'Soil needs of Mango',
    soilSci: 'Deep, fertile, well-drained loams preferred; avoids prolonged waterlogging.',
    soilImp: 'Soil drainage controls root health and canopy cooling services.',
    soilEx: 'Farm plantings succeed on raised beds where monsoon water drains.',
    soilFact: 'Compacted urban pits shorten mango lifespan.',
    soilCons: 'Soil sealing around roots cuts infiltration and oxygen.',
    ecoShort: 'Ecosystem role of Mango',
    ecoSci: 'Provides fruit, shade, litter for soil organic matter, and farm livelihood value (FAO/ICRAF framing).',
    ecoImp: 'Mango supports nutrition and microclimate beyond ornamental planting.',
    ecoEx: 'Homestead mango trees are dual food + shade assets.',
    ecoFact: 'Leaf litter builds soil carbon under the canopy.',
    ecoCons: 'Clearing mango collapses both food and shade services together.',
    bioShort: 'Wildlife links to Mango',
    bioSci: 'Flowers attract insects; ripe fruit feeds birds, bats, and squirrels.',
    bioImp: 'Fruiting mango creates seasonal food pulses for urban wildlife.',
    bioEx: 'Park managers keep fruiting trees for frugivore habitat.',
    bioFact: 'Bats can disperse mango seeds over long distances.',
    bioCons: 'Felling during peak fruiting removes a key wildlife food source.',
    pollShort: 'Pollinator value of Mango',
    pollSci: 'Mango panicles support bees and other insects that assist fruit set.',
    pollImp: 'Pollinator visits raise fruit yield and neighborhood forage diversity.',
    pollEx: 'Orchard IPM avoids spraying during peak bloom.',
    pollFact: 'Good pollination improves fruit size uniformity.',
    pollCons: 'Insecticide on open flowers can crash local bee forage.',
    carbonSciExtra: 'FSI/TOF framing counts mango in farm/urban tree-cover carbon narratives.',
    carbonEx: 'Municipal inventories include mango in outdoor tree carbon tallies.',
    shadeShort: 'Cooling services of Mango',
    shadeSci: 'Dense mango canopy intercepts solar radiation and cools ground surfaces beneath.',
    shadeImp: 'Shade from mango can reduce local heat stress near homes and paths.',
    shadeEx: 'Villages retain mango on courtyards for summer comfort.',
    shadeFact: 'A broad mango crown often out-shades slender palms of similar age.',
    shadeCons: 'Replacing mature mango with saplings creates a multi-year heat gap.',
    medShort: 'Medicinal profile of Mango',
    medSci: 'Traditional uses include leaves, bark, seed kernel, and unripe fruit; phytochemicals include mangiferin and polyphenols (verify clinically).',
    medImp: 'Medicinal claims must stay tied to Mangifera indica chemistry.',
    medEx: 'Folk preparations cite specific mango parts rather than generic “tree bark”.',
    medFact: 'Mangiferin is a frequently cited mango polyphenol.',
    medCons: 'Over-harvesting bark from wild/semi-wild trees can damage trunks.',
    culShort: 'Cultural role of Mango',
    culSci: 'Mango is a cultural fruit tree of prosperity and festivals across South Asia.',
    culImp: 'Cultural value often protects mango when purely timber trees are cut.',
    culEx: 'Festival and homestead traditions center on mango fruit and leaves.',
    culFact: 'Mango is widely called the king of fruits in India.',
    culCons: 'Ignoring cultural attachment can trigger community conflict over felling.',
    pestShort: 'Health risks for Mango',
    pestSci: 'Common issues: mango hopper, fruit fly, anthracnose, powdery mildew.',
    pestImp: 'Unmanaged pests reduce growth, fruiting, and carbon gain.',
    pestEx: 'IPM calendars target hopper and anthracnose windows specifically for mango.',
    pestFact: 'Fruit fly damage spikes in warm humid fruiting seasons.',
    pestCons: 'Severe outbreaks can kill productive canopy branches.',
    consShort: 'Stewardship priority for Mango',
    consSci: 'Retain mature mango in farms, temples, and urban TOF for food + canopy continuity.',
    consImp: 'Even common cultivated mango is valuable at site scale for shade and nutrition.',
    consEx: 'City tree policies can list mango as retain/replace priority.',
    consFact: 'Old mango cultivars may be rare even if the species is common.',
    consCons: '“Common species” is not a reason to clear healthy mature mango.',
    factShort: 'Notable points about Mango',
    factSci: 'FAO/ICRAF/USDA/GBIF-framed mango profile emphasizes fruit, shade, and South Asian cultivar richness.',
    factImp: 'Species-true facts help communities defend mango retention.',
    factEx: 'Extension stories about mango outperform generic “trees are good” messaging.',
    factFact: 'One mature mango can feed a household and cool a courtyard for decades.',
    factCons: 'Share mango-specific value when opposing unnecessary felling.',
    medicinalJson: {
      compounds: ['Mangiferin', 'Polyphenols', 'Carotenoids', 'Vitamin C (fruit)'],
      applications: ['Traditional leaf/bark decoctions', 'Culinary unripe fruit uses', 'Seed-kernel folk preparations'],
      diseases: ['Digestive discomfort (traditional)', 'Skin applications (folk)', 'General antioxidant dietary use'],
      description:
        'Mango (Mangifera indica) carries traditional medicinal and nutritional uses centered on leaves, bark, seed kernel, and fruit. Modern phytochemistry highlights mangiferin and polyphenols; clinical use should be evidence-checked.',
    },
    habitatJson: {
      birds: ['Rose-ringed Parakeet (Psittacula krameri)', 'Coppersmith Barbet (Psilopogon haemacephalus)', 'Asian Koel (Eudynamys scolopaceus)'],
      insects: ['Honey bees (Apis spp.)', 'Fruit flies (watch pests)', 'Native butterflies at bloom'],
      mammals: ['Indian Flying Fox (Pteropus giganteus)', 'Palm squirrels (Funambulus spp.)'],
      description:
        'Mango canopies feed frugivores with ripe fruit and support insect activity at flowering, linking homestead orchards to urban wildlife corridors.',
    },
  }),
};

// Compact generator for remaining species to keep file maintainable but complete
function quickPack(common, scientific, family, hooks) {
  return pack(common, scientific, family, {
    idShort: `How to recognize ${common}`,
    idSci: hooks.id,
    idImp: `Correct ${common} ID keeps climatic and medicinal claims species-accurate.`,
    idEx: hooks.idEx || `Survey lists register ${common} as ${scientific}.`,
    idFact: hooks.idFact || `Scientific name used here: ${scientific}.`,
    idCons: `Replacing mature ${common} erases a verified canopy asset.`,
    taxEx: `GBIF/USDA-style records place ${common} in family ${family}.`,
    taxFact: hooks.taxFact || `${common} aliases: ${(hooks.aliases || []).join(', ') || common}.`,
    descShort: `Physical form of ${common}`,
    descSci: hooks.desc,
    descImp: `${common} structure drives shade, biomass, and wildlife use.`,
    descEx: `Field ID of ${common} uses leaf/crown traits during GBH surveys.`,
    descFact: hooks.descFact || `${common} has a distinctive growth habit vs other dropdown species.`,
    descCons: `Cutting mature ${common} removes decades of architecture.`,
    habShort: `Where ${common} grows best`,
    habSci: hooks.hab,
    habImp: `Site matching raises ${common} survival and carbon performance.`,
    habEx: hooks.habEx || `Agroforestry and urban plantings site ${common} for climate fit.`,
    habFact: hooks.habFact || `${common} fails faster on waterlogged compacted soils.`,
    habCons: `Wrong habitat planting wastes ${common} stock.`,
    distShort: `Where ${common} is recorded`,
    distSci: hooks.dist,
    distImp: `Range knowledge guides whether ${common} is native priority or amenity planting.`,
    distEx: `GBIF / India Biodiversity Portal notes inform ${common} distribution.`,
    distFact: hooks.distFact || `${common} occurrence is shaped by cultivation as much as wild spread.`,
    distCons: `Local provenances of ${common} outperform random stock.`,
    climShort: `Climate niche of ${common}`,
    climSci: hooks.clim,
    climImp: `Climate fit determines long-term sequestration by ${common}.`,
    climEx: `FAO-style guidance uses climate envelopes for ${common}.`,
    climFact: hooks.climFact || `${common} stress shows first in leaf scorch or tip dieback.`,
    climCons: `Climate mismatch increases irrigation and mortality risk.`,
    soilShort: `Soil needs of ${common}`,
    soilSci: hooks.soil,
    soilImp: `Soil drainage controls ${common} root health and canopy services.`,
    soilEx: `ICRAF farm notes recommend suitable soils for ${common}.`,
    soilFact: hooks.soilFact || `Urban soil compaction is a top limiter for ${common}.`,
    soilCons: `Sealed surfaces starve ${common} roots of water and air.`,
    ecoShort: `Ecosystem role of ${common}`,
    ecoSci: hooks.eco,
    ecoImp: `${common} provides species-specific shade/livelihood/habitat services.`,
    ecoEx: hooks.ecoEx || `Programs count ${common} in greening and livelihood plans.`,
    ecoFact: hooks.ecoFact || `${common} litter and shade alter local microclimates.`,
    ecoCons: `Removing ${common} collapses its unique service bundle.`,
    bioShort: `Wildlife links to ${common}`,
    bioSci: hooks.bio,
    bioImp: `${common} supports fauna that may not use every street tree equally.`,
    bioEx: `Biodiversity plantings include ${common} for habitat structure.`,
    bioFact: hooks.bioFact || `Flower/fruit seasons of ${common} create wildlife pulses.`,
    bioCons: `Felling ${common} in peak bloom/fruit removes forage.`,
    pollShort: `Pollinator value of ${common}`,
    pollSci: hooks.poll,
    pollImp: `Pollinators using ${common} boost local forage diversity.`,
    pollEx: `Avoid insecticide on ${common} during flowering.`,
    pollFact: hooks.pollFact || `${common} flowers can be an important seasonal nectar source.`,
    pollCons: `Spray at bloom can eliminate bee visits to ${common}.`,
    carbonSciExtra: hooks.carbonExtra || `FSI/TOF framing includes ${common} in tree-cover carbon narratives.`,
    carbonEx: `Inventories include ${common} in outdoor carbon tallies.`,
    shadeShort: `Cooling services of ${common}`,
    shadeSci: hooks.shade,
    shadeImp: `Shade from ${common} reduces local heat exposure.`,
    shadeEx: `Designers place ${common} on heat-facing edges for canopy form.`,
    shadeFact: hooks.shadeFact || `${common} shade quality differs from palms and slender conifers.`,
    shadeCons: `Replacing mature ${common} with saplings creates a heat gap.`,
    medShort: `Medicinal profile of ${common}`,
    medSci: hooks.med,
    medImp: `Medicinal claims must stay tied to ${scientific}.`,
    medEx: `Cite specific ${common} plant parts in traditional notes.`,
    medFact: hooks.medFact || `Phytochemistry of ${common} is species-specific.`,
    medCons: `Over-harvesting ${common} parts can injure living trees.`,
    culShort: `Cultural role of ${common}`,
    culSci: hooks.cul,
    culImp: `Cultural protection often keeps ${common} standing.`,
    culEx: hooks.culEx || `Community traditions may center on ${common}.`,
    culFact: hooks.culFact || `${common} carries local naming and use identity.`,
    culCons: `Ignoring cultural status of ${common} risks conflict.`,
    pestShort: `Health risks for ${common}`,
    pestSci: hooks.pest,
    pestImp: `Pests reduce ${common} growth and carbon gain if ignored.`,
    pestEx: `IPM for ${common} should target named pests, not generic spray.`,
    pestFact: hooks.pestFact || `Humid seasons often worsen fungal issues on ${common}.`,
    pestCons: `Severe outbreaks can kill ${common} canopy sections.`,
    consShort: `Stewardship priority for ${common}`,
    consSci: hooks.cons,
    consImp: `Site-scale protection of ${common} preserves shade and carbon.`,
    consEx: `Municipal lists can mark ${common} as retain/replace priority.`,
    consFact: hooks.consFact || `Mature ${common} is harder to replace than seedlings imply.`,
    consCons: `Do not clear healthy ${common} without replacement planning.`,
    factShort: `Notable points about ${common}`,
    factSci: hooks.factSci || `Local multi-source pack for ${common} (${scientific}).`,
    factImp: `Species-true facts help defend ${common} retention.`,
    factEx: `Extension messaging should feature ${common}-specific benefits.`,
    factFact: hooks.factFact || `${scientific} is the scientific handle for ${common}.`,
    factCons: `Share ${common}-specific value when opposing unnecessary felling.`,
    medicinalJson: hooks.medicinalJson,
    habitatJson: hooks.habitatJson,
    aliases: hooks.aliases,
  });
}

Object.assign(PACKS, {
  Bamboo: quickPack('Bamboo', 'Bambusa vulgaris', 'Poaceae', {
    aliases: ['Common bamboo'],
    id: 'Bambusa vulgaris is a clumping tropical bamboo with tall woody culms and rapid vegetative growth.',
    desc: 'Fast-growing culm clumps used for construction, crafts, and land binding.',
    hab: 'Moist tropical sites, riverbanks, and farm edges with fertile soils.',
    dist: 'Tropical Asia origin with wide cultivation across the tropics.',
    clim: 'Warm humid climates with good moisture; limited frost tolerance.',
    soil: 'Fertile moist soils; rhizomes need space and moisture without stagnation.',
    eco: 'FAO/ICRAF value bamboo for biomass, erosion control, and rural materials.',
    bio: 'Dense culm clumps shelter birds and insects; litter feeds decomposers.',
    poll: 'Bamboo flowering is infrequent; ecological value is more structural habitat than nectar.',
    shade: 'Culm clumps reduce wind and shade ground, aiding microclimate control.',
    med: 'Shoots enter traditional diets; medicinal claims should stay modest and verified.',
    cul: 'Strong craft and housing traditions across India use bamboo.',
    pest: 'Culm borers and fungal culm rot appear under poor management.',
    cons: 'Protect rhizomes during harvest so clumps regenerate.',
    carbonExtra: 'High annual increment makes bamboo a fast biomass carbon crop.',
    medicinalJson: {
      compounds: ['Dietary fiber (shoots)', 'Silica-rich tissues', 'Phenolics (variable)'],
      applications: ['Edible shoot cuisine', 'Traditional material culture', 'Land restoration plantings'],
      diseases: ['Mostly nutritional/traditional uses rather than primary drug claims'],
      description: 'Bamboo (Bambusa vulgaris) is primarily a material and biomass species; shoot use is culinary/traditional, with restoration value for slopes and farms.',
    },
    habitatJson: {
      birds: ['Bulbuls nesting in thickets', 'Tailorbirds in dense cover'],
      insects: ['Culm-associated beetles', 'Generalist pollinators on rare bloom'],
      mammals: ['Small mammals using thicket cover'],
      description: 'Bamboo clumps create dense cover and windbreaks that shelter birds and insects in farm and village edges.',
    },
  }),
  Christmas: quickPack('Christmas', 'Araucaria columnaris', 'Araucariaceae', {
    aliases: ['Cook pine', 'Christmas tree'],
    id: 'Araucaria columnaris is a columnar evergreen conifer used as a tropical “Christmas tree” ornamental.',
    desc: 'Tall spire form with scale-like leaves; distinctive columnar silhouette.',
    hab: 'Warm coastal and urban ornamental plantings with well-drained soils.',
    dist: 'Native New Caledonia; cultivated in tropical cities worldwide.',
    clim: 'Tropical/subtropical maritime climates; dislikes severe frost.',
    soil: 'Well-drained sandy to loamy soils; avoid waterlogging.',
    eco: 'Mainly amenity structure and evergreen visual screening.',
    bio: 'Provides perch/roost structure for urban birds.',
    poll: 'Wind-related conifer ecology; limited bee-forage role vs flowering hardwoods.',
    shade: 'Narrow columnar shade; useful as vertical accent more than broad cooling.',
    med: 'Not a primary medicinal tree; ornamental value dominates.',
    cul: 'Used as festive/ornamental Christmas tree in warm regions.',
    pest: 'Scale insects and tip dieback under drought or poor drainage.',
    cons: 'Retain healthy specimens in campuses/parks for evergreen structure.',
    medicinalJson: {
      compounds: ['Resinous terpenes (general conifer chemistry)'],
      applications: ['Ornamental landscaping', 'Campus/park vertical accents'],
      diseases: ['Not used as a major medicinal species'],
      description: 'Christmas/Cook pine (Araucaria columnaris) is an ornamental conifer; climatic analysis focuses on evergreen structure and urban amenity rather than drug use.',
    },
    habitatJson: {
      birds: ['Urban pigeons/roosting birds on tall leaders', 'Mynas using nearby canopy'],
      insects: ['Scale insects (pest watch)', 'General urban arthropods'],
      mammals: ['Limited; mostly bird perch habitat'],
      description: 'Columnar araucarias add vertical roost structure in urban plantings more than fruit/nectar resources.',
    },
  }),
  'Palm (Bottle Palm)': quickPack('Palm (Bottle Palm)', 'Hyophorbe lagenicaulis', 'Arecaceae', {
    aliases: ['Bottle palm', 'Palm'],
    id: 'Hyophorbe lagenicaulis is an ornamental palm with a swollen bottle-like trunk and pinnate fronds.',
    desc: 'Slow–moderate growth; distinctive bottle trunk used in tropical landscaping.',
    hab: 'Tropical ornamental beds and coastal gardens; full sun; well-drained soils.',
    dist: 'Native lineage from Mascarene islands; cultivated ornamentally worldwide.',
    clim: 'Strictly tropical; frost intolerant.',
    soil: 'Sandy loams with good drainage; sensitive to stagnant water.',
    eco: 'Amenity palm contributing to tropical garden structure.',
    bio: 'Inflorescences may attract insects; limited cavity habitat vs native palms.',
    poll: 'Insects may visit flowers; not a major honey species.',
    shade: 'Fronds cast localized shade; less broad cooling than mango/rain tree.',
    med: 'Not a major medicinal palm.',
    cul: 'Popular statement palm in public landscapes.',
    pest: 'Palm pests include scale and regional lethal yellowing-type risks.',
    cons: 'Protect rare ornamental stock; avoid trunk injury.',
    medicinalJson: {
      compounds: ['Typical palm metabolites (not a primary medicinal species)'],
      applications: ['Ornamental landscaping'],
      diseases: ['N/A as primary medicine'],
      description: 'Bottle palm is primarily ornamental; climatic impact focuses on trunk biomass and local frond shade.',
    },
    habitatJson: {
      birds: ['Occasional perching birds on fronds'],
      insects: ['Scale insects', 'Floral visitors'],
      mammals: ['Minimal direct use'],
      description: 'Bottle palms add tropical structure; wildlife value is modest compared with fruiting native trees.',
    },
  }),
  Coconut: quickPack('Coconut', 'Cocos nucifera', 'Arecaceae', {
    aliases: ['Nariyal', 'Coconut palm'],
    id: 'Cocos nucifera is a tall coastal palm producing coconuts, oil, coir, and shade.',
    desc: 'Single stem palm with long pinnate fronds and large fibrous drupes.',
    hab: 'Coastal plains and irrigated tropics; salt-spray tolerant; needs warmth.',
    dist: 'Pantropical cultivated distribution with dense Asian coastal records.',
    clim: 'Hot humid lowlands; no frost tolerance.',
    soil: 'Sandy coastal to loamy soils with moisture; tolerates salinity better than most trees.',
    eco: 'FAO cornerstone crop palm for food, fiber, and coastal livelihoods.',
    bio: 'Inflorescences attract insects; fronds may host epiphytes in humid coasts.',
    poll: 'Insects and wind contribute; flowers support insect activity.',
    shade: 'Frond shade cools ground strips along coasts and farms.',
    med: 'Water, oil, and kernel used in traditional diets/remedies; lauric-rich oil profile.',
    cul: 'Ritual and daily-life palm across India (Nariyal).',
    pest: 'Rhinoceros beetle, red palm weevil, mites; regional lethal diseases.',
    cons: 'Retain mature palms in coastal TOF and homestead systems.',
    medicinalJson: {
      compounds: ['Lauric acid', 'Medium-chain triglycerides', 'Electrolytes (water)'],
      applications: ['Culinary oil', 'Hydrating coconut water', 'Traditional oil applications'],
      diseases: ['Supportive traditional uses; not a cure-all'],
      description: 'Coconut provides nutritional and traditional oil/water uses; climatic value includes coastal livelihood and shade strips.',
    },
    habitatJson: {
      birds: ['Coastal crows/mynas', 'Occasional nesting in nearby canopy'],
      insects: ['Inflorescence visitors', 'Palm pests (monitor)'],
      mammals: ['Humans as primary users; rodents on fallen nuts'],
      description: 'Coconut groves structure coastal agroecosystems and support insect activity at flowering.',
    },
  }),
  Ashoka: quickPack('Ashoka', 'Saraca asoca', 'Fabaceae', {
    aliases: ['Sita Ashok', 'Sorrowless tree'],
    id: 'Saraca asoca is a small evergreen sacred tree with dense foliage and orange-red flowers.',
    desc: 'Compound leaves, hanging coppery young flush, fragrant corymb flowers, flat pods.',
    hab: 'Humid tropics, stream margins, shaded gardens; moisture-retentive soils.',
    dist: 'South Asia native; temple and garden cultivation common in India.',
    clim: 'Humid tropical monsoon climates; low drought tolerance.',
    soil: 'Deep loamy soils with organic matter; avoid extreme drought stress.',
    eco: 'Sacred ornamental providing dense evergreen shade and nectar resources.',
    bio: 'Nectar-rich flowers support bees, sunbirds, and butterflies.',
    poll: 'Strong pollinator value during bloom.',
    shade: 'Dense evergreen shade cools small courtyards and temple precincts.',
    med: 'Bark traditionally used in Ayurveda for gynecological formulations; tannins/flavonoids noted.',
    cul: 'Sacred “without sorrow” tree in Hindu/Buddhist traditions.',
    pest: 'Leaf caterpillars and fungal spots in humid shade.',
    cons: 'Wild populations are conservation-sensitive; prefer cultivated stock.',
    medicinalJson: {
      compounds: ['Tannins', 'Flavonoids', 'Sterols'],
      applications: ['Traditional uterine tonics', 'Ayurvedic bark preparations'],
      diseases: ['Traditional gynecological indications (clinical supervision required)'],
      description: 'Ashoka bark is historically important in Ayurveda; conserve wild trees and prefer cultivated sources.',
    },
    habitatJson: {
      birds: ['Purple Sunbird (Cinnyris asiaticus)', 'Red-whiskered Bulbul (Pycnonotus jocosus)'],
      insects: ['Honey bees', 'Blue Mormon and other butterflies'],
      mammals: ['Palm squirrels in dense canopy'],
      description: 'Ashoka’s evergreen nectar-rich canopy supports sunbirds, bees, and butterflies in gardens and sacred groves.',
    },
  }),
  'Tej Patta': quickPack('Tej Patta', 'Cinnamomum tamala', 'Lauraceae', {
    aliases: ['Indian bay leaf', 'Tejpat'],
    id: 'Cinnamomum tamala is an aromatic evergreen Lauraceae tree harvested for culinary bay leaves.',
    desc: 'Aromatic leaves used as Tej Patta; related to the cinnamon group.',
    hab: 'Subtropical Himalayan foothills and moist farm edges; cooler than deep-coast tropics.',
    dist: 'Himalayan foothills and NE India with cultivation for leaf spice.',
    clim: 'Cooler subtropical moist climates; dislikes extreme arid heat.',
    soil: 'Moist, well-drained forest soils rich in organic matter.',
    eco: 'NTFP leaf species supporting culinary markets and homestead agroforestry.',
    bio: 'Aromatic flowers/leaves support specialist insects.',
    poll: 'Insect visitors on aromatic blooms.',
    shade: 'Evergreen leaf canopy gives moderate homestead shade.',
    med: 'Leaves used in traditional digestive/aromatic preparations; eugenol-type oils vary by chemotype.',
    cul: 'Staple culinary leaf across Indian cooking.',
    pest: 'Leaf miners and fungal leaf blight in dense humidity.',
    cons: 'Sustainable leaf harvest should not strip entire crowns.',
    medicinalJson: {
      compounds: ['Essential oils', 'Eugenol-type constituents (chemotype-dependent)', 'Aromatics'],
      applications: ['Culinary spice leaf', 'Traditional aromatic digestive uses'],
      diseases: ['Traditional digestive comfort uses'],
      description: 'Tej Patta leaves are culinary-aromatic with traditional digestive associations; chemotypes vary.',
    },
    habitatJson: {
      birds: ['Foothill forest birds using mid-canopy'],
      insects: ['Specialist aromatic-plant insects', 'Generalist pollinators'],
      mammals: ['Small mammals in farm-forest edges'],
      description: 'Tej Patta plantings enrich homestead biodiversity while supplying culinary leaves.',
    },
  }),
  Badam: quickPack('Badam', 'Terminalia catappa', 'Combretaceae', {
    aliases: ['Indian almond', 'Tropical almond'],
    id: 'Terminalia catappa is a coastal shade tree with pagoda branching and large leaves that flush red.',
    desc: 'Layered crown, large leaves, edible seeds; strong avenue shade form.',
    hab: 'Coastal sands, avenues, parks; salt tolerant; full sun.',
    dist: 'Pantropical coastal cultivation and naturalization.',
    clim: 'Tropical coastal climates; heat loving.',
    soil: 'Sandy to loamy well-drained soils; tolerates coastal conditions.',
    eco: 'FAO/ICRAF coastal shade, edible kernel, and shoreline amenity tree.',
    bio: 'Seeds/fruit feed birds and rodents; broad canopy for nesting shade.',
    poll: 'Insects visit flowers; shade structure aids urban fauna.',
    shade: 'Excellent broad shade cooling for streets and coasts.',
    med: 'Leaves used in folk remedies; tannins present.',
    cul: 'Popular “Badam” shade tree identity in Indian coasts/cities.',
    pest: 'Leaf beetles and sooty mold in humid cities.',
    cons: 'Retain large avenue specimens for shade continuity.',
    medicinalJson: {
      compounds: ['Tannins', 'Flavonoids'],
      applications: ['Folk leaf preparations', 'Shade/amenity forestry'],
      diseases: ['Traditional skin/folk uses (verify)'],
      description: 'Indian almond (Badam) is mainly a shade/coastal amenity tree with tannin-rich leaves in folk use.',
    },
    habitatJson: {
      birds: ['Mynas', 'Crows', 'Frugivorous birds on seeds'],
      insects: ['Leaf beetles (pest watch)', 'Floral visitors'],
      mammals: ['Rodents on fallen seeds'],
      description: 'Badam avenues create wide shade corridors and seed resources for urban birds and rodents.',
    },
  }),
  'Rain Tree': quickPack('Rain Tree', 'Samanea saman', 'Fabaceae', {
    aliases: ['Monkey pod', 'Cow tamarind'],
    id: 'Samanea saman is a wide-canopy tropical shade tree with bipinnate leaves and pods.',
    desc: 'Umbrella crown, nitrogen-fixing Fabaceae, classic pasture/avenue shade tree.',
    hab: 'Tropical lowlands, avenues, parks, pastures; deep soils preferred.',
    dist: 'Neotropical native; extensively cultivated across tropical Asia including India.',
    clim: 'Hot lowland tropics; thrives with rainfall or irrigation.',
    soil: 'Deep soils; benefits from nitrogen fixation in agroforestry.',
    eco: 'Silvopastoral shade and urban cooling giant.',
    bio: 'Pods feed livestock/wildlife; canopy nests for birds.',
    poll: 'Flowers support insects; massive canopy hosts biodiversity.',
    shade: 'Exceptional shade cooling across wide crown diameters.',
    med: 'Regional traditional pod/leaf uses; not a primary AYUSH drug tree.',
    cul: 'Iconic city “rain tree” shade identity.',
    pest: 'Sap-suckers/sooty mold; storm branch breakage risk.',
    cons: 'Protect large specimens; replacement takes decades.',
    medicinalJson: {
      compounds: ['Leaf/pod phenolics (general)'],
      applications: ['Shade forestry', 'Silvopasture'],
      diseases: ['Limited primary medicinal claims'],
      description: 'Rain tree is chiefly a climate-cooling and pasture-shade species with massive canopy services.',
    },
    habitatJson: {
      birds: ['Urban nesting birds in broad crowns', 'Parakeets'],
      insects: ['Floral visitors', 'Sap-sucking pests (monitor)'],
      mammals: ['Squirrels', 'Livestock feeding on pods'],
      description: 'Rain tree crowns are biodiversity platforms in cities and farms, offering nest sites and pod forage.',
    },
  }),
  'Silver Oak': quickPack('Silver Oak', 'Grevillea robusta', 'Proteaceae', {
    aliases: ['Silky oak'],
    id: 'Grevillea robusta is a fast-growing plantation/shade tree with fern-like leaves and orange flowers.',
    desc: 'Australian native widely used as coffee/tea shade and farm forestry tree.',
    hab: 'Subtropical highlands to warm plantings; well-drained soils.',
    dist: 'Native eastern Australia; naturalized/cultivated in India and Africa.',
    clim: 'Warm temperate to subtropical; dislikes waterlogging.',
    soil: 'Well-drained soils; sensitive to poor drainage.',
    eco: 'ICRAF classic shade tree for plantations; pruneable canopy.',
    bio: 'Nectar-rich flowers attract sunbirds and bees.',
    poll: 'Strong bird/bee nectar resource when flowering.',
    shade: 'Light filtered shade suited to understorey crops.',
    med: 'Not a major medicinal tree.',
    cul: 'Estate/avenue identity in Indian hill plantings.',
    pest: 'Borers and cankers under stress; root competition if unpruned.',
    cons: 'Manage pruning to balance shade and crop light.',
    medicinalJson: {
      compounds: ['Limited medicinal emphasis'],
      applications: ['Plantation shade', 'Farm forestry timber/shade'],
      diseases: ['N/A as primary medicine'],
      description: 'Silver oak is valued for fast biomass and plantation shade rather than medicinal chemistry.',
    },
    habitatJson: {
      birds: ['Sunbirds on nectar', 'Hill mynas/other nectar feeders'],
      insects: ['Bees on orange blooms'],
      mammals: ['Limited direct; plantation edge fauna'],
      description: 'Flowering silver oak is a nectar beacon for sunbirds and bees in plantation landscapes.',
    },
  }),
  Supari: quickPack('Supari', 'Areca catechu', 'Arecaceae', {
    aliases: ['Betel nut', 'Areca nut'],
    id: 'Areca catechu is a slender plantation palm grown for arecanut (supari).',
    desc: 'Tall thin stem, pinnate fronds, orange-red seeds in fibrous husk.',
    hab: 'Humid tropics and heavy rainfall belts; rich irrigated soils.',
    dist: 'Cultivated across South/Southeast Asia; dense Indian arecanut belts.',
    clim: 'Hot humid climates with high rainfall or irrigation.',
    soil: 'Fertile, moisture-retentive but managed soils.',
    eco: 'Major cash-crop palm; often intercropped in homesteads.',
    bio: 'Inflorescences attract insects; monocultures need intercrops for diversity.',
    poll: 'Insect activity at flowering supports plantation ecology.',
    shade: 'Vertical palm rows create strip shade in plantations.',
    med: 'Traditional stimulant nut; public-health cautions for habitual chewing; arecoline/tannins present.',
    cul: 'Ritual offerings and social uses across India.',
    pest: 'Fruit rot, spindle bug, yellow leaf disease complexes.',
    cons: 'Diversify plantations to reduce disease and biodiversity loss.',
    medicinalJson: {
      compounds: ['Arecoline', 'Tannins'],
      applications: ['Traditional ceremonial nut use', 'Cultural offerings'],
      diseases: ['Health cautions for habitual chewing (public health)'],
      description: 'Supari/arecanut has strong cultural use; health guidance advises caution with habitual consumption.',
    },
    habitatJson: {
      birds: ['Plantation edge birds'],
      insects: ['Inflorescence visitors', 'Pest complexes (monitor)'],
      mammals: ['Rodents on fallen nuts'],
      description: 'Arecanut plantations structure humid farm landscapes; intercrops improve wildlife value.',
    },
  }),
  Ad: quickPack('Ad', 'Ad', 'Unknown', {
    aliases: ['Ad'],
    id: 'Local vernacular “Ad” — scientific identity unresolved in catalog; confirm with local botanist for precise claims.',
    desc: 'Morphology depends on verified species; record leaf/bark/fruit in the field.',
    hab: 'Collect site notes on soil moisture and light for this local tree.',
    dist: 'Treat as regional vernacular until mapped to a scientific name.',
    clim: 'Use measured performance on site rather than assumed climate niche.',
    soil: 'Observe drainage and rooting depth on the actual planting site.',
    eco: 'Document local multipurpose uses from community knowledge carefully.',
    bio: 'Field observation required for wildlife associations.',
    poll: 'Observe floral visitors during bloom if present.',
    shade: 'Measure canopy shade from the actual crown, not a template species.',
    med: 'Do not invent medicinal claims; record community reports with caution.',
    cul: 'Capture local naming and any ritual context.',
    pest: 'Scout and record pests locally.',
    cons: 'Keep the tree until identity is confirmed; avoid misapplied treatments.',
    carbonExtra: 'Use measured GBH/height allometrics until wood density is confirmed.',
    medicinalJson: {
      compounds: ['Unknown until species confirmed'],
      applications: ['Document local reports only'],
      diseases: ['No unverified medical claims'],
      description: 'Ad is a vernacular label in this app. Confirm scientific identity before asserting medicinal chemistry.',
    },
    habitatJson: {
      birds: ['Observe on site'],
      insects: ['Observe on site'],
      mammals: ['Observe on site'],
      description: 'Habitat associations for Ad require field confirmation after botanical identification.',
    },
  }),
  Bel: quickPack('Bel', 'Aegle marmelos', 'Rutaceae', {
    aliases: ['Bael', 'Wood apple'],
    id: 'Aegle marmelos is a sacred fruit tree with trifoliate leaves and hard-shelled bael fruit.',
    desc: 'Deciduous to semi-evergreen; trifoliate leaves; woody fruit used in food/tradition.',
    hab: 'Dry to moist deciduous zones, plains, temple gardens; needs drainage.',
    dist: 'Native South Asia; widely cultivated near temples and villages.',
    clim: 'Tolerates heat and seasonal drought once established.',
    soil: 'Wide soil tolerance if drainage is adequate.',
    eco: 'Homestead fruit/medicinal tree with cultural protection.',
    bio: 'Flowers support insects; fruit feeds wildlife when available.',
    poll: 'Insect visitors on fragrant blooms.',
    shade: 'Medium stature shade for yards and temple precincts.',
    med: 'Fruit and leaves used in traditional digestive remedies; coumarins/alkaloids reported.',
    cul: 'Sacred to Lord Shiva; trifoliate leaves used in worship.',
    pest: 'Fruit borer and fungal fruit rots in humid conditions.',
    cons: 'Retain sacred/homestead bel trees; they are slow to replace culturally.',
    medicinalJson: {
      compounds: ['Coumarins', 'Alkaloids', 'Fruit mucilage/fiber'],
      applications: ['Traditional digestive fruit preparations', 'Leaf ritual/traditional uses'],
      diseases: ['Traditional digestive support uses'],
      description: 'Bel/bael is a culturally sacred Rutaceae fruit tree with traditional digestive associations.',
    },
    habitatJson: {
      birds: ['Frugivorous birds when fruit softens', 'Temple-garden birds'],
      insects: ['Floral visitors', 'Fruit pests (monitor)'],
      mammals: ['Squirrels', 'Occasional fruit foraging mammals'],
      description: 'Bel trees in temples and homesteads support insects at flowering and occasional frugivory on fruit.',
    },
  }),
});

export function getLocalSpeciesPack(speciesName) {
  const meta = resolveSpeciesMeta(speciesName);
  const packObj = PACKS[meta.common] || PACKS[speciesName];
  if (!packObj) return null;
  return packObj;
}

export function buildLocalClimateSummary(speciesName, age, biomass, carbon, co2) {
  const packObj = getLocalSpeciesPack(speciesName);
  if (!packObj) return null;
  return packObj.climate(age, biomass, carbon, co2);
}

export function buildLocalMedicinalSummary(speciesName) {
  const packObj = getLocalSpeciesPack(speciesName);
  if (!packObj) return null;
  return packObj.medicinal;
}

export function buildLocalHabitatSummary(speciesName) {
  const packObj = getLocalSpeciesPack(speciesName);
  if (!packObj) return null;
  return packObj.habitat;
}

export { PIPELINE as LOCAL_RESEARCH_PIPELINE };
